deploy_composer:
  image: curlimages/curl
  only:
    - tags
  stage: test
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "Deploy-Token: ${DEPLOY_TOKEN}" "https://git.kobaltdigital.nl/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
