deploy_composer:
  image: curlimages/curl
  only:
    - tags
  stage: test
  script:
    - curl --data tag=${CI_COMMIT_TAG} "https://__token__:${TOKEN}@git.kobaltdigital.nl/api/v4/projects/203/packages/composer"
